release:
  branches:
    - master

plugins:
  -
    - '@semantic-release/commit-analyzer'
    - preset: conventionalcommits
      presetConfig: {}
  - '@semantic-release/release-notes-generator'
  -
    - semantic-release-vsce
    - packageVsix: yolodev-jsonnet-build-tasks.vsix
  - '@semantic-release/github'
